#ifndef _OSGEARTH_HEADER_H__
#define _OSGEARTH_HEADER_H__
#pragma warning(disable:4100)

#include <osgEarthUtil/AutoClipPlaneHandler>
#include <osgEarth/Cache>
#include <osgEarthUtil/Common>
#include <osgEarthAnnotation/CircleNode>
#include <osgEarthUtil/Controls>
#include <osgEarth/CullingUtils>
#include <osgEarth/ElevationQuery>
#include <osgEarthUtil/ExampleResources>
#include <osgEarthUtil/EarthManipulator>
#include <osgEarthAnnotation/EllipseNode>
#include <osgEarthFeatures/Feature>
#include <osgEarthFeatures/FeatureMaskLayer>
#include <osgEarthAnnotation/FeatureNode>
#include <osgEarth/GeoData>
#include <osgEarth/GeoMath>
#include <osgEarthFeatures/GeometryUtils>
#include <osgEarth/GeoTransform>
#include <osgEarth/GLUtils>
#include <osgEarth/HttpClient>
#include <osgEarthUtil/HTM>
#include <osgEarthAnnotation/ImageOverlay>
#include <osgEarth/ImageUtils>
#include <osgEarth/IntersectionPicker>
#include <osgEarth/JsonUtils>
#include <osgEarthAnnotation/LabelNode>
#include <osgEarth/optional>
#include <osgEarth/Lighting>
#include <osgEarth/MapNode>
#include <osgEarth/MaskLayer>
#include <osgEarth/ModelSource>
#include <osgEarthUtil/MGRSFormatter>
//#include <osgEarthFeatures/OgrUtils>
#include <osgEarthAnnotation/PlaceNode>
#include <osgEarth/PhongLightingEffect>
#include <osgEarth/Random>
#include <osgEarth/Registry>
#include <osgEarthAnnotation/RectangleNode>
#include <osgEarth/Shadowing>
#include <osgEarth/ShaderUtils>
#include <osgEarth/ShaderLoader>
#include <osgEarth/SpatialReference>
#include <osgEarthSymbology/Symbol>
#include <osgEarthSymbology/Style>
#include <osgEarth/StringUtils>
#include <osgEarth/TDTiles>
#include <osgEarth/TerrainEffect>
#include <osgEarth/TerrainEngineNode>
#include <osgEarthFeatures/TessellateOperator>
#include <osgEarth/URI>
#include <osgEarth/Units>
#include <osgEarth/Viewpoint>
#include <osgEarth/VirtualProgram>
#include <osgEarth/XmlUtils>
#include <osgEarth/LandCover>
#include <osgEarth/LandCoverLayer>
#include <osgEarth/VideoLayer>
#include <osgEarthAnnotation/AnnotationLayer>
#include <osgEarthFeatures/FeatureModelLayer>
#include <osgEarthFeatures/ImageToFeatureLayer>
#include <osgEarthSplat/GroundCoverLayer>
#include <osgEarthSplat/RoadSurfaceLayer>
#include <osgEarthSplat/SplatLayer>
#include <osgEarthUtil/FlatteningLayer>
#include <osgEarthUtil/FractalElevationLayer>
#include <osgEarthUtil/GARSGraticule>
#include <osgEarthUtil/GeodeticGraticule>
#include <osgEarthUtil/MGRSGraticule>
#include <osgEarthUtil/MultiElevationLayer>
#include <osgEarthUtil/SimpleOceanLayer>
#include <osgEarthUtil/SimpleOceanLayer>
#include <osgEarthUtil/UTMGraticule>


#define TDTILES osgEarth::TDTiles

#endif
