 #pragma once

#define ICON_BMP_0_NOVISABLE									0
#define ICON_BMP_1_NOVISABLE									1
#define ICON_BMP_2_VISABLE										2
#define ICON_BMP_3_COM_ELEMENT_NODATA_NOEDIT					3
#define ICON_BMP_4_COM_ELEMENT_NODATA_EDIT						4
#define ICON_BMP_5_COM_ELEMENT_DATA_NOEDIT						5
#define ICON_BMP_6_COM_ELEMENT_DATA_EDIT						6
#define ICON_BMP_7_COM_LAYER_NODATA_NOEDIT						7
#define ICON_BMP_8_COM_LAYER_NODATA_EDIT						8
#define ICON_BMP_9_COM_LAYER_DATA_NOEDIT						9
#define ICON_BMP_10_COM_LAYER_DATA_EDIT							10
#define ICON_BMP_11_SQL_ELEMENT_NODATA_NOEDIT					11
#define ICON_BMP_12_SQL_ELEMENT_NODATA_EDIT						12
#define ICON_BMP_13_SQL_ELEMENT_DATA_NOEDIT						13
#define ICON_BMP_14_SQL_ELEMENT_DATA_EDIT						14
#define ICON_BMP_15_GEOMAP_ELEMENT_NODATA_NOEDIT				15
#define ICON_BMP_16_GEOMAP_ELEMENT_NODATA_EDIT					16
#define ICON_BMP_17_GEOMAP_ELEMENT_DATA_NOEDIT					17
#define ICON_BMP_18_GEOMAP_ELEMENT_DATA_EDIT					18
#define ICON_BMP_19_SQL_LAYER_NODATA_NOEDIT						19
#define ICON_BMP_20_SQL_LAYER_NODATA_EDIT						20
#define ICON_BMP_21_SQL_LAYER_DATA_NOEDIT						21
#define ICON_BMP_22_SQL_LAYER_DATA_EDIT							22
#define ICON_BMP_23_GEOMAP_LAYER_NODATA_NOEDIT					23
#define ICON_BMP_24_GEOMAP_LAYER_NODATA_EDIT					24
#define ICON_BMP_25_GEOMAP_LAYER_DATA_NOEDIT					25
#define ICON_BMP_26_GEOMAP_LAYER_DATA_EDIT						26
#define ICON_BMP_27_3DLABLE_LAYER_NODATA_NOEDIT					27
#define ICON_BMP_28_3DLABLE_LAYER_NODATA_EDIT					28
#define ICON_BMP_29_3DLABLE_LAYER_DATA_NOEDIT					29
#define ICON_BMP_30_3DLABLE_LAYER_DATA_EDIT						30
#define ICON_BMP_31_3DFEATURE_LAYER_NODATA_NOEDIT				31
#define ICON_BMP_32_3DFEATURE_LAYER_NODATA_EDIT					32
#define ICON_BMP_33_3DFEATURE_LAYER_DATA_NOEDIT					33
#define ICON_BMP_34_3DFEATURE_LAYER_DATA_EDIT					34
#define ICON_BMP_35_3DFEATURE_ELEMENT_NODATA_NOEDIT				35
#define ICON_BMP_36_3DFEATURE_ELEMENT_NODATA_EDIT				36
#define ICON_BMP_37_3DFEATURE_ELEMENT_DATA_NOEDIT				37
#define ICON_BMP_38_3DFEATURE_ELEMENT_DATA_EDIT					38
#define ICON_BMP_39_ROOT										39
#define ICON_BMP_40_PRJLIST_EDIT_ELEMENT						40


