 #pragma once

#define ICON_BMP_0_NOVISABLE									0
#define ICON_BMP_1_NOVISABLE									1
#define ICON_BMP_2_VISABLE										2
#define ICON_BMP_3_COM_ELEMENT_NODATA_NOEDIT					3
#define ICON_BMP_4_COM_ELEMENT_NODATA_EDIT						4
#define ICON_BMP_5_COM_ELEMENT_DATA_NOEDIT						5
#define ICON_BMP_6_COM_ELEMENT_DATA_EDIT						6
#define ICON_BMP_7_COM_LAYER_NODATA_NOEDIT						7
#define ICON_BMP_8_COM_LAYER_NODATA_EDIT						8
#define ICON_BMP_9_COM_LAYER_DATA_NOEDIT						9
#define ICON_BMP_10_COM_LAYER_DATA_EDIT							10
#define ICON_BMP_11_SQL_ELEMENT_NODATA_NOEDIT					11
#define ICON_BMP_12_SQL_ELEMENT_NODATA_EDIT						12
#define ICON_BMP_13_SQL_ELEMENT_DATA_NOEDIT						13
#define ICON_BMP_14_SQL_ELEMENT_DATA_EDIT						14
#define ICON_BMP_15_GEOMAP_ELEMENT_NODATA_NOEDIT				15
#define ICON_BMP_16_GEOMAP_ELEMENT_NODATA_EDIT					16
#define ICON_BMP_17_GEOMAP_ELEMENT_DATA_NOEDIT					17
#define ICON_BMP_18_GEOMAP_ELEMENT_DATA_EDIT					18
#define ICON_BMP_19_SQL_LAYER_NODATA_NOEDIT						19
#define ICON_BMP_20_SQL_LAYER_NODATA_EDIT						20
#define ICON_BMP_21_SQL_LAYER_DATA_NOEDIT						21
#define ICON_BMP_22_SQL_LAYER_DATA_EDIT							22
#define ICON_BMP_23_GEOMAP_LAYER_NODATA_NOEDIT					23
#define ICON_BMP_24_GEOMAP_LAYER_NODATA_EDIT					24
#define ICON_BMP_25_GEOMAP_LAYER_DATA_NOEDIT					25
#define ICON_BMP_26_GEOMAP_LAYER_DATA_EDIT						26
#define ICON_BMP_27_3DLABLE_LAYER_NODATA_NOEDIT					27
#define ICON_BMP_28_3DLABLE_LAYER_NODATA_EDIT					28
#define ICON_BMP_29_3DLABLE_LAYER_DATA_NOEDIT					29
#define ICON_BMP_30_3DLABLE_LAYER_DATA_EDIT						30
#define ICON_BMP_31_3DFEATURE_LAYER_NODATA_NOEDIT				31
#define ICON_BMP_32_3DFEATURE_LAYER_NODATA_EDIT					32
#define ICON_BMP_33_3DFEATURE_LAYER_DATA_NOEDIT					33
#define ICON_BMP_34_3DFEATURE_LAYER_DATA_EDIT					34
#define ICON_BMP_35_3DFEATURE_ELEMENT_NODATA_NOEDIT				35
#define ICON_BMP_36_3DFEATURE_ELEMENT_NODATA_EDIT				36
#define ICON_BMP_37_3DFEATURE_ELEMENT_DATA_NOEDIT				37
#define ICON_BMP_38_3DFEATURE_ELEMENT_DATA_EDIT					38
#define ICON_BMP_39_ROOT										39
#define ICON_BMP_40_PRJLIST_EDIT_ELEMENT						40

#define ICON_BMP_2DDATASOURCE_NORMAL						     0  //基础数据源	
#define ICON_BMP_3DMODEL_NORMAL						            15  //三维模型
#define ICON_BMP_DB_NORMAL			   			                19  //数据库	
#define ICON_BMP_BASEMAP_NORMAL									 1  //基础地理底图
#define ICON_BMP_MAP_NORMAL										 2  //地理底图
#define ICON_BMP_IMG_NORMAL									     3  //遥感影像
#define ICON_BMP_STDSTRATSET_NORMAL                              4  //标准地层集
#define ICON_BMP_STDSTRATSET_ACTIVE								 1	
#define ICON_BMP_STDSTRATS_NORMAL								 5 //标准地层
#define ICON_BMP_STDSTRATS_ACTIVE								 3
#define ICON_BMP_STDSTRATSUB_NORMAL								 13 //
#define ICON_BMP_STDSTRATSUB_ACTIVE								 5
#define ICON_BMP_HOLE_NORMAL									 6  //钻孔
#define ICON_BMP_HOLE_ACTIVE									 7
#define ICON_BMP_GEOMAP_NORMAL									 7  //地质图
#define ICON_BMP_GEOMAP_ACTIVE									 9  
#define ICON_BMP_GEOPNT_NORMAL									 8  //地质点
#define ICON_BMP_GEOPNT_ACTIVE									 11
#define ICON_BMP_ORIENETATIONPNT_NORMAL							 9 //产状点
#define ICON_BMP_ORIENETATIONPNT_ACTIVE							 13
#define ICON_BMP_GEOBOUND_NORMAL								 10 //地质界线
#define ICON_BMP_GEOBOUND_ACTIVE								 15
#define ICON_BMP_STRATREGION_NORMAL                              11 //地层区
#define ICON_BMP_STRATREGION_ACTIVE                              11
#define ICON_BMP_HOLELOCALLINE_NORMAL							 13 //钻孔轨迹线
#define ICON_BMP_HOLELOCALLINE_ACTIVE							 17
#define ICON_BMP_SECTIONMAPSET_NORMAL							 12	//剖面图集合	 						 
#define ICON_BMP_SECTIONMAPSET_ACTIVE							 19
#define ICON_BMP_SECTIONMAP_NORMAL								 12  //剖面图
#define ICON_BMP_SECTIONMAP_ACTIVE								 21
#define ICON_BMP_MININGLEVELMAPSET_NORMAL						 14	//中段图集合	 
#define ICON_BMP_MININGLEVELMAPSET_ACTIVE						 23
#define ICON_BMP_MININGLEVELMAP_NORMAL							 14	 //中段图
#define ICON_BMP_MININGLEVELMAP_ACTIVE							 25 
#define ICON_BMP_STRATBOUNDMAP_NORMAL							 14  //地层分区图
#define ICON_BMP_STRATBOUNDMAP_ACTIVE							 27
#define ICON_BMP_GEOBODYSTRUCTURE_NORMAL						 16  //地质体结构
#define ICON_BMP_STRATCFACE_NORMAL						         17  //地层面				     
#define ICON_BMP_ATTRIBUTEFIELD_NORMAL						     18  //属性场				     
#define ICON_BMP_STDSTRAT_NORMAL								 20  //标准地层最后一层
#define ICON_BMP_STDSTRAT_ACTIVE								  3
#define ICON_BMP_DEM_NORMAL										 21  //DEM数据
#define ICON_BMP_DEM_ACTIVE										  3	

